tagFormat: "${version}"
branches:
    - "+([0-9])?(.{+([0-9]),x}).x"
    - { name: "master", prerelease: false }
    - { name: "next", prerelease: true, channel: "next" }
plugins:
    - "@semantic-release/commit-analyzer"
    - "@semantic-release/release-notes-generator"
    - "@semantic-release/changelog"
    - - "@semantic-release/exec"
      - prepareCmd: sed -i 's/.*/${nextRelease.version}/g' version
    - - "@semantic-release/git"
      - message: "chore(release): ${nextRelease.version}\n\n${nextRelease.notes}"
        assets:
            - CHANGELOG.md
            - version
    - - "@saithodev/semantic-release-backmerge"
      - branchName: next
